{{- if .Values.postgresql.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "odoo-hospital.pgPvcName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "odoo-hospital.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  accessModes:
    - {{ .Values.postgresql.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.postgresql.persistence.size }}
  storageClassName: {{ .Values.postgresql.persistence.storageClass }}
{{- end }}
