apiVersion: v1
kind: Service
metadata:
  name: {{ include "odoo-hospital.fullname" . }}-postgres
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "odoo-hospital.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  type: ClusterIP
  selector:
    {{- include "odoo-hospital.pgSelectorLabels" . | nindent 4 }}
  ports:
    - name: postgres
      port: {{ .Values.postgresql.service.port }}
      targetPort: 5432
      protocol: TCP
